# Generated by Django 5.1 on 2025-02-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(max_length=32)),
                ('imagens', models.JSONField(default=list)),
                ('equipe', models.PositiveIntegerField(default=1)),
                ('tecnologias', models.TextField()),
                ('periodo', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('repo', models.CharField(max_length=64)),
            ],
        ),
    ]
