# Generated by Django 5.1 on 2025-02-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='figma',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
