# Generated by Django 5.1 on 2025-02-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_projetos_figma'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='website',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
